import { Drink } from '../../interfaces/drinks.interfaces';
import { transformObject } from '../../utils/drinks.utils.ts';

describe('transformObject', () => {
    it('должен корректно преобразовывать объект с ингредиентами и мерами', () => {
        const input: Drink = {
            idDrink: '1',
            strDrink: 'Test Cocktail',
            strIngredient1: 'Rum',
            strMeasure1: '50ml',
            strIngredient2: 'Lime Juice',
            strMeasure2: '30ml',
            strIngredient3: null,
            strMeasure3: null,
            strDrinkThumb: '',
            strInstructions: '',
            strCategory: '',
            strAlcoholic: '',
            strGlass: '',
            dateModified: null,
            strDrinkAlternate: null,
            strTags: 'IBA,ContemporaryClassic',
            strVideo: null,
            strIBA: null,
            strInstructionsES: null,
            strInstructionsDE: 'Gib die Creme de Cassis auf den Boden des Glases und füge dann Wein hinzu.',
            strInstructionsFR: null,
            strInstructionsIT: 'Aggiungere la crème de cassis sul fondo del bicchiere, quindi rabboccare con il vino.',
            strInstructionsZH_HANS: '',
            strInstructionsZH_HANT: '',
            strIngredient4: null,
            strIngredient5: null,
            strIngredient6: null,
            strIngredient7: null,
            strIngredient8: null,
            strIngredient9: null,
            strIngredient10: null,
            strIngredient11: null,
            strIngredient12: null,
            strIngredient13: null,
            strIngredient14: null,
            strIngredient15: null,
            strMeasure4: null,
            strMeasure5: null,
            strMeasure6: null,
            strMeasure7: null,
            strMeasure8: null,
            strMeasure9: null,
            strMeasure10: null,
            strMeasure11: null,
            strMeasure12: null,
            strMeasure13: null,
            strMeasure14: null,
            strMeasure15: null,
            strImageSource: null,
            strImageAttribution: null,
            strCreativeCommonsConfirmed: 'No',
        };

        const result = transformObject(input);

        expect(result).toEqual([
            { key: 1, measure: '50ml', ingredient: 'Rum' },
            { key: 2, measure: '30ml', ingredient: 'Lime Juice' },
        ]);
    });

    it('должен игнорировать пустые или null значения ингредиентов', () => {
        const input: Drink = {
            idDrink: '2',
            strDrink: 'Another Test',
            strIngredient1: 'Gin',
            strMeasure1: null,
            strIngredient2: null,
            strMeasure2: '10ml',
            strDrinkThumb: '',
            strInstructions: '',
            strCategory: '',
            strAlcoholic: '',
            strGlass: '',
            dateModified: null,
            strDrinkAlternate: null,
            strTags: 'IBA,ContemporaryClassic',
            strVideo: null,
            strIBA: null,
            strInstructionsES: null,
            strInstructionsDE: 'Gib die Creme de Cassis auf den Boden des Glases und füge dann Wein hinzu.',
            strInstructionsFR: null,
            strInstructionsIT: 'Aggiungere la crème de cassis sul fondo del bicchiere, quindi rabboccare con il vino.',
            strInstructionsZH_HANS: '',
            strInstructionsZH_HANT: '',
            strIngredient3: null,
            strIngredient4: null,
            strIngredient5: null,
            strIngredient6: null,
            strIngredient7: null,
            strIngredient8: null,
            strIngredient9: null,
            strIngredient10: null,
            strIngredient11: null,
            strIngredient12: null,
            strIngredient13: null,
            strIngredient14: null,
            strIngredient15: null,
            strMeasure3: null,
            strMeasure4: null,
            strMeasure5: null,
            strMeasure6: null,
            strMeasure7: null,
            strMeasure8: null,
            strMeasure9: null,
            strMeasure10: null,
            strMeasure11: null,
            strMeasure12: null,
            strMeasure13: null,
            strMeasure14: null,
            strMeasure15: null,
            strImageSource: null,
            strImageAttribution: null,
            strCreativeCommonsConfirmed: 'No',
        };

        const result = transformObject(input);

        expect(result).toEqual([{ key: 1, measure: null, ingredient: 'Gin' }]);
    });

    it('должен возвращать пустой массив, если нет ингредиентов', () => {
        const input: Drink = {
            idDrink: '3',
            strDrink: 'Empty Test',
            strDrinkThumb: '',
            strInstructions: '',
            strCategory: '',
            strAlcoholic: '',
            strGlass: '',
            dateModified: null,
            strDrinkAlternate: null,
            strTags: 'IBA,ContemporaryClassic',
            strVideo: null,
            strIBA: null,
            strInstructionsES: null,
            strInstructionsDE: 'Gib die Creme de Cassis auf den Boden des Glases und füge dann Wein hinzu.',
            strInstructionsFR: null,
            strInstructionsIT: 'Aggiungere la crème de cassis sul fondo del bicchiere, quindi rabboccare con il vino.',
            strInstructionsZH_HANS: '',
            strInstructionsZH_HANT: '',
            strIngredient1: null,
            strIngredient2: null,
            strIngredient3: null,
            strIngredient4: null,
            strIngredient5: null,
            strIngredient6: null,
            strIngredient7: null,
            strIngredient8: null,
            strIngredient9: null,
            strIngredient10: null,
            strIngredient11: null,
            strIngredient12: null,
            strIngredient13: null,
            strIngredient14: null,
            strIngredient15: null,
            strMeasure1: null,
            strMeasure2: null,
            strMeasure3: null,
            strMeasure4: null,
            strMeasure5: null,
            strMeasure6: null,
            strMeasure7: null,
            strMeasure8: null,
            strMeasure9: null,
            strMeasure10: null,
            strMeasure11: null,
            strMeasure12: null,
            strMeasure13: null,
            strMeasure14: null,
            strMeasure15: null,
            strImageSource: null,
            strImageAttribution: null,
            strCreativeCommonsConfirmed: 'No',
        };

        const result = transformObject(input);

        expect(result).toEqual([]);
    });
});
